######################################################################
# Automatically generated by qmake (2.01a) gio apr 9 21:11:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h gameboard.h lcdrange.h
SOURCES += cannonfield.cpp gameboard.cpp lcdrange.cpp main.cpp
